# ==========================================
# 1. CADASTRO BASE DE ITENS (LISTA COMPLETA COM 42 ITENS)
# ==========================================
if "cat" not in st.session_state:
    st.session_state.cat = pd.DataFrame([
        {"ID": 1, "Material": "CIMENTO LAFARGE FONDU", "Lote": "09/07/25_1400kg", "Fabricacao": "2025-07-09", "Validade": "12 Meses", "Unidade": "KG", "QtdPorPalete": 1400.0, "Status": "Ativo"},
        {"ID": 2, "Material": "CARBETO DE SILICIO", "Lote": "LOTE-CS-1000", "Fabricacao": "2025-01-10", "Validade": "Indeterminada", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 3, "Material": "ARGAMASSA REFRATÁRIA TECNOFIRE 50S (1200kg)", "Lote": "TEC-50S-1200", "Fabricacao": "2025-02-01", "Validade": "6 Meses", "Unidade": "KG", "QtdPorPalete": 1200.0, "Status": "Ativo"},
        {"ID": 3, "Material": "ARGAMASSA REFRATÁRIA TECNOFIRE 50S (400kg)", "Lote": "TEC-50S-400", "Fabricacao": "2025-02-01", "Validade": "6 Meses", "Unidade": "KG", "QtdPorPalete": 400.0, "Status": "Ativo"},
        {"ID": 3, "Material": "ARGAMASSA REFRATÁRIA PLACIBAR SG (1250kg)", "Lote": "PLAC-SG-1250", "Fabricacao": "2025-02-06", "Validade": "6 Meses", "Unidade": "KG", "QtdPorPalete": 1250.0, "Status": "Ativo"},
        {"ID": 3, "Material": "ARGAMASSA REFRATÁRIA PLACIBAR SG (1000kg)", "Lote": "PLAC-SG-1000", "Fabricacao": "2025-02-06", "Validade": "6 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 4, "Material": "CASTIBAR PSI UG (1250kg)", "Lote": "CAST-UG-1250", "Fabricacao": "2025-03-01", "Validade": "12 Meses", "Unidade": "KG", "QtdPorPalete": 1250.0, "Status": "Ativo"},
        {"ID": 4, "Material": "CASTIBAR PSI UG (1000kg)", "Lote": "CAST-UG-1000", "Fabricacao": "2025-03-01", "Validade": "12 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 5, "Material": "LÃ DE ROCHA IBAR SEM CORTE", "Lote": "LA-ROCHA-SC", "Fabricacao": "2025-01-01", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 5, "Material": "LÃ DE ROCHA IBAR CORTADO", "Lote": "LA-ROCHA-C", "Fabricacao": "2025-01-01", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 6, "Material": "TIJOLO SEMI ISOLANTE SUPRA SKAMOL ALUPOROS-910", "Lote": "SKAMOL-910", "Fabricacao": "2025-01-15", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 6, "Material": "TIJOLO SEMI ISOLANTE SUPRA MOSCONI AB70-1020", "Lote": "MOSCONI-1020", "Fabricacao": "2025-01-15", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 7, "Material": "TIJOLO ISOLANTE SKAMOL ALUPOROS 912", "Lote": "SKAMOL-912", "Fabricacao": "2025-01-20", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 7, "Material": "TIJOLO ISOLANTE MOSCONI AB 55-680", "Lote": "MOSCONI-680", "Fabricacao": "2025-01-20", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 8, "Material": "TIJOLO REFRATÁRIO SA ALUM 512", "Lote": "ALUM-512", "Fabricacao": "2025-01-25", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 8, "Material": "TIJOLO REFRATÁRIO VESUVIUS 336", "Lote": "VESU-336", "Fabricacao": "2025-01-25", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 8, "Material": "TIJOLO REFRATÁRIO VESUVIUS 416 [CHINA]", "Lote": "VESU-416", "Fabricacao": "2025-01-25", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 8, "Material": "TIJOLO REFRATÁRIO VESUVIUS 296 [CHINA]", "Lote": "VESU-296", "Fabricacao": "2025-01-25", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 11, "Material": "CHAMOTE IBAR", "Lote": "CHAMOTE-IBAR", "Fabricacao": "2025-03-01", "Validade": "Indeterminada", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 11, "Material": "CHAMOTE TecFire", "Lote": "CHAMOTE-TEC", "Fabricacao": "2025-03-01", "Validade": "Indeterminada", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 12, "Material": "PASTA FRIA ELKEN T30- REMENDO 74630_74631", "Lote": "74630_74631", "Fabricacao": "2025-03-10", "Validade": "3 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 12, "Material": "PASTA FRIA REMENDO 75074_75075 A 75085_75087", "Lote": "75074_75087", "Fabricacao": "2025-03-10", "Validade": "3 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 12, "Material": "PASTA FRIA 75949_75952", "Lote": "75949_75952", "Fabricacao": "2025-03-10", "Validade": "3 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 12, "Material": "PASTA FRIA 76007_76010", "Lote": "76007_76010", "Fabricacao": "2025-03-10", "Validade": "3 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 12, "Material": "PASTA FRIA ELKEN 76323_76328", "Lote": "76323_76328", "Fabricacao": "2025-03-10", "Validade": "3 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 12, "Material": "PASTA FRIA ELKEN 76069_76086", "Lote": "76069_76086", "Fabricacao": "2025-03-10", "Validade": "3 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 12, "Material": "PASTA FRIA LOTES 76030_76037 e 76062_76067", "Lote": "76030_76067", "Fabricacao": "2025-03-10", "Validade": "3 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 12, "Material": "PASTA FRIA CARBON LOTE 759", "Lote": "CARBON-759", "Fabricacao": "2025-03-10", "Validade": "3 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 12, "Material": "PASTA FRIA CARBON LOTE 763", "Lote": "CARBON-763", "Fabricacao": "2025-03-10", "Validade": "3 Meses", "Unidade": "KG", "QtdPorPalete": 1000.0, "Status": "Ativo"},
        {"ID": 13, "Material": "ITEM 13 (VAZIO)", "Lote": "-", "Fabricacao": "2025-03-15", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 14, "Material": "BLOCOS LATERAL CARBON", "Lote": "BL-CARBON", "Fabricacao": "2025-01-05", "Validade": "Indeterminada", "Unidade": "CX", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 15, "Material": "BLOCOS ENGUSADOS/FUNDO ANEXA BLOCOS ENGUSADOS SEC", "Lote": "ENG-SEC-ANEXA", "Fabricacao": "2025-04-01", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 15, "Material": "BLOCOS ENGUSADOS/FUNDO BARRACAO BLOCOS ENGUSADOS SEC", "Lote": "ENG-SEC-BAR", "Fabricacao": "2025-04-01", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 15, "Material": "BLOCOS ENGUSADOS/FUNDO BARRACAO BLOCO DE FUNDO ENERGOPRON", "Lote": "ENERGOPRON", "Fabricacao": "2025-04-01", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 15, "Material": "BLOCOS ENGUSADOS/FUNDO BARRACAO BLOCOS DE FUNDO TOKAYCOBEX", "Lote": "TOKAYCOBEX-15", "Fabricacao": "2025-04-01", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 16, "Material": "BARRAS CATÓDICAS ANEXA", "Lote": "BAR-ANEXA", "Fabricacao": "2025-04-05", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 16, "Material": "BARRAS CATÓDICAS BARRACAO", "Lote": "BAR-BARRACAO", "Fabricacao": "2025-04-05", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 16, "Material": "BARRAS CATÓDICAS BARRACAO TESTE (1)", "Lote": "BAR-TESTE-1", "Fabricacao": "2025-04-05", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 16, "Material": "BARRAS CATÓDICAS BARRACAO TESTE (2)", "Lote": "BAR-TESTE-2", "Fabricacao": "2025-04-05", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 17, "Material": "BLOCOS DE FUNDO SEC BARRACÃO", "Lote": "BL-SEC-BAR", "Fabricacao": "2025-04-10", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 17, "Material": "BLOCOS DE FUNDO SEC BARRACAO TOKAYCOBEX", "Lote": "TOKAYCOBEX-17", "Fabricacao": "2025-04-10", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"},
        {"ID": 17, "Material": "BLOCOS DE FUNDO SEC ANEXA", "Lote": "BL-SEC-ANEXA", "Fabricacao": "2025-04-10", "Validade": "Indeterminada", "Unidade": "UN", "QtdPorPalete": 1.0, "Status": "Ativo"}
    ])
            st.rerun()
